### ISSUE TITLE
TypeError on repository code with Windows System

### ISSUE THREAD

**Issue by kgdthomas** [alecsandrei/PySAGA-cmd#3]
I have been attempting to run this code which is just a directory change from your posted code on the page:

`from PySAGA_cmd import SAGA

# Initialize SAGA command line interface
saga = SAGA(r"C://Program Files//SAGA//saga_cmd.exe")

# Choosing libraries.
preprocessor = saga / 'ta_preprocessor'

# Choosing tools.
route_detection = preprocessor / 'Sink Drainage Route Detection'`

but it keeps showing a TypeError.

"---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[17], line 7
      4 saga = SAGA(r"C://Program Files//SAGA//saga_cmd.exe")
      6 # Choosing libraries.
----> 7 preprocessor = saga / 'ta_preprocessor'
      9 # Choosing tools.
     10 route_detection = preprocessor / 'Sink Drainage Route Detection'

TypeError: unsupported operand type(s) for /: 'SAGA' and 'str'" 

![image](https://github.com/user-attachments/assets/451ceb7f-43c5-45c3-9623-9ee797f5e817)

**Comment by alecsandrei** [comment]
Hello Thomas, thank you for posting the issue!

Can you confirm you are on the latest version of PySAGA-cmd (1.2.6)? You can do that using the _pip freeze_ command or by looking inside the site-packages folder.

**Comment by kgdthomas** [comment]
This issue seems to be related to using the installed base conda Python. I tested it on an alternative Python installation in a special environment and it worked without repeating the issue on the first PC. My second PC which does not have an anaconda installation had no issues from the first stage. Consider this resolved with the caveat:

"Check your Python if you see this issue"
